name: beatsync_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: 5.2.1
  cupertino_icons: 1.0.8
  flutter_secure_storage: 9.0.0
  equatable: 2.0.5
  dartz: 0.10.1
  dio: 5.4.3+1
  get_it: 7.7.0
  google_fonts: ^6.2.1
  go_router: 15.1.2
  flutter_bloc: 8.1.6
  shared_preferences: 2.2.3
  flutter_hooks: 0.20.5
  rive: 0.13.20
  camera: 0.10.5+5
  fl_chart: ^0.65.0
  heart_bpm: ^2.0.0+0
  permission_handler: ^11.0.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  device_info_plus: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  intl: 0.19.0


flutter:

  generate: true
  uses-material-design: true

  
  assets:
    - assets/
    - assets/rive/
    - assets/lottie/
